INSERT INTO tb_genre (name) VALUES ('Drama, Thriller');
INSERT INTO tb_genre (name) VALUES ('Faroeste');
INSERT INTO tb_genre (name) VALUES ('Ação, Aventura');
INSERT INTO tb_genre (name) VALUES ('Fantasia, Terror');
INSERT INTO tb_genre (name) VALUES ('Guerra, Ação, Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção científica, Terror');
INSERT INTO tb_genre (name) VALUES ('Ação, Ficção científica, Thriller, Mistério');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Ficção científica, Ação, Thriller');
INSERT INTO tb_genre (name) VALUES ('Família');

INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Em Busca de Vingança','Para ele era só o que restava', 'Inspirado em acontecimentos reais, conta a história de dois estranhos – Roman Melnyk, um chefe de construção e Jake Bonanos, um controlador de tráfego aéreo – cujas vidas se unem depois de um acidente de avião que resultou na morte da esposa e da filha de Roman.', 2017, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oWmsQTZx1MNu7iX0zc0yCJ0a6Ck.jpg', 1);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Três Homens em Conflito','Para três homens, a Guerra Civil não era o inferno. Era prática.', 'Três homens que ganham a vida de forma questionável no velho oeste norte-americano sabem da existência de um magnífico tesouro enterrado; o problema é que cada um conhece apenas uma parte do segredo para encontrá-lo e nenhum deles está disposto a fazer um acordo para dividi-lo. Nesse cenário conflituoso os três tentarão encontrar uma forma de, ao mesmo tempo, descobrir o que os outros sabem e ser o primeiro a chegar ao prêmio.',1966, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f6CoXpyZRqYJF3lTfxjWIahO6qM.jpg', 2);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('O Reino das Espadas',NULL, 'Nos tempos das cruzadas e da Horda Dourada, um poder surgiu na Europa Central, uma força tão grande que não pode ser ignorada. O príncipe Roman, o Grande, uniu as terras vizinhas. Os cavaleiros teutônicos chamavam o reino de Principado da Rutênia. No auge de seu domínio, Roman foi morto em uma emboscada. Os Boyars aproveitaram essa oportunidade para dividir o poder entre si. Yefrosinia, esposa do príncipe Roman, filha do imperador de Constantinopla, usou sua influência para salvar seus filhos. As terras rutenas se afogaram no derramamento de sangue da guerra, até que os filhos do príncipe, Danylo e Vasylko, deram um passo à frente e recuperaram o legado de seu pai.', 2018, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1s7iFKwIJ1Skk9poFBZf4P0yQ9U.jpg', 3);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Caçador de Demônios',NULL, 'Quando um antigo demônio é acidentalmente libertado sobre a pequena população de Chickory Creek no Mississippi, a única esperança de sobrevivência está nas mãos de um caçador de demônios grisalho Jebediah Woodley (Dolph Lundgren) e sua parceira relutante, a agente do FBI Evelyn Pierce.', 2016, 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/acfhS1No3R9rG4amSwmGg4tklKz.jpg',4 );
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Lobo Guerreiro 2',NULL, 'Depois de realizar uma ação contra uma perigosa organização criminosa e eliminar o filho de um grande traficante, Leng Feng, um soldado do batalhão de forças especiais da China, foi perseguido e terminou se aposentando quando a ameaça acabou. Agora, Feng vive tranquilamente em um barco. Quando um grupo de mercenários começa a atacar um povoado perto de onde Feng está atracado, o ex,soldado se vê obrigado a voltar à ativa, uma vez que jurou proteger os inocentes. Um novo duelo tem início e o inimigo será mais feroz do que nunca!', 2017 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/nJ8V8eOLWEKnZjvRZkyI8BRMKDf.jpg',5);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Parasita - Parte 1',NULL, 'A história se passa em um mundo em que seres extraterrestres chamados parasitas invadem a Terra. Eles se apoderam dos humanos entrando pelas cavidades corporais, com a finalidade de controlar o corpo da vítima. A história se desenrola quando um extraterrestre chamado Migi falha em se apoderar do corpo de Shinichi Izumi, fazendo com que os dois sejam obrigados a conviver juntos.',2014 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ho6i1UIO5sbbwJbCWQbZxxTP9XR.jpg',6 );
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Um Dia para Viver','Contratado para matar. Lutando para sobreviver.', 'Um assassino (Ethan Hawke) ganha uma segunda chance quando seu empregador o traz de volta à vida temporariamente, logo após ter sido morto no trabalho. Ele ganha então 24 horas para realizar sua missão e se redimir.',2017 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yyr8u7wQU2k7HpJvBeGmZsJkZTR.jpg', 7 );
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('On Your Wedding Day','Do you remember? Your first love.', 'Through the course of their lives, a man and his first love are repeatedly separated from each other because of circumstances out of their control.', 2017 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oOzH5nyyHMMDlwOAupnn4itIgCL.jpg', 8);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Autodestruição','Os mundos vão colidir', 'A história acontece num mundo futurista, onde o piloto esta lutando para salvar sua família após um experimento por energia ilimitada e controle de universos paralelos dar errado. A ficção científica é baseada no curta "What’s in the Box?", de Tim Smit, e tem seu roteiro escrito por Charlie Kindinger e Omid Nooshin.',2017 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2A3FETGysWKyYREI3YGzfpNKr8K.jpg', 9);
INSERT INTO tb_movie (title, sub_title, synopsis ,year, img_url, genre_id) VALUES ('Um Acampamento do Barulho','Face Your Fears!', 'Em um acampamento cristão para jovens, as crianças aprendem a lidar com seus medos e não a procurar a violência para resolver o problema. Dois irmãos são separados em duas casas diferentes e, depois de uma série de pegadinhas promovidas pelos valentões do local, eles percebem que precisam um do outro. Quando chega a hora de disputar uma importante competição do acampamento, os garotos precisam colocar de lado suas diferenças se quiserem, além de vencer o torneio, aprender o verdadeiro valor do respeito, do perdão e da convivência em paz entre as pessoas.',2017 , 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3MKctBpU3fobuCpFsjN3xBwUcDh.jpg',10 );

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user (name, email, password, role_id) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$12$RnqR2z4J4s2BF1Wji18gZu5hk1Sn5nJGbKUPUx8NhZIhbiY2HX2am', 1);
INSERT INTO tb_user (name, email, password, role_id) VALUES ('Ana Green', 'ana@gmail.com', '$2a$12$RnqR2z4J4s2BF1Wji18gZu5hk1Sn5nJGbKUPUx8NhZIhbiY2HX2am', 2);